### ISSUE TITLE
Some sensor Data wrong values?

### ISSUE THREAD

**Issue by Track4123** [tp1de/ioBroker.ems-esp#33]
Hi, first thanks for the great great work! The solution of the Bosch is in fact crap compared on whats possible here ;-)
Looks some sensor data (chimney, hotwater_t2, supply_T1_setpoint, switch) have some incorrect information.
See data with value 3200. Data are read from the KM200.

![image](https://github.com/tp1de/ioBroker.ems-esp/assets/144127021/946b0039-852e-4680-ac74-eae590bbe3f9)

**Comment by tp1de** [comment]
The adapter takes the data 1:1 from the api interface. 

And yes some data might be wrong when sensor is not existing and/or processed from the gateway. Don't forget, Bosch does not want us to use this undocumented (encrypted) api interface.

**Comment by Track4123** [comment]
Mmh, Ok, then it is an Bosch issue. I expect getting some new measures from the KM200 is to be done by Bosch!?  Looking for values like the return temp from the HC,( Special Sensor), temp Buffer middle, switch if buffer supplies into HC, yes,no and the position of the mixer. Values come from modules SM200 and MM50

**Comment by tp1de** [comment]
Return temp depends on system - if there is a sensor or not. If a sensor is available it has to be supported of the gateway firmware version. 

KM200 and similar gateways are end of life and are not produced anymore. The new gateways only support cloud access with very limited data available ... and I believe that users need to pay in the future. 
So do not expect any further developments.

An alternate gateway is the ems-esp (around 100 €) where much more data points are available. If interested check if your boiler and thermostat is supported. Dallas sensors can be connected (e.g. return temp), if no internal sensor is available.
For my mm100 this gateway reports the mixer valve position, but I can't change because it's controlled by the RC310 thermostat.

**Comment by Track4123** [comment]
Thx. Indeed, I also  considered to get EMS-ESP already. I will get it a trial one day; for now I will try out the KM200 further. The ioBroker Adapter is better than everthing Bosch has done till now, so top!
