### ISSUE TITLE
Green Lamp - Gateway unreachable

### ISSUE THREAD

**Issue by unstressable** [tp1de/ioBroker.ems-esp#39]
Actually the adapter doesn't show if the ems-esp gateway is reachable:
<img width="179" alt="image" src="https://github.com/tp1de/ioBroker.ems-esp/assets/50423935/e1b7168c-d361-427f-aa01-a6328b8abf3a">

Today my gateway get stuck, and I didn't recognize, because the lamp was green.

Isn't there a possibility to make it like this:
<img width="185" alt="image" src="https://github.com/tp1de/ioBroker.ems-esp/assets/50423935/04e1183a-0435-4106-a327-7aa6dffe0290">

**Comment by tp1de** [comment]
I tried my best to implement. Since the adapter supports 2 gateways parallel (ems-esp and km200) and there is only one connection status available, the status shows availability of one gateway as an error.

Within the states under info.connection and  info_connection__ems / info.connectio_km200 the details can be seen.

You can test by installing the latest version from Github. Please report if any disconnection is properly seen.

**Comment by unstressable** [comment]
so you did something for this in the latest version?

I mean, you could implement it like the adapter only checks the checkmarked gateways.

**Comment by tp1de** [comment]
Please install the version from GH and give a Feedback.

**Comment by unstressable** [comment]
Looks good actually.

**Comment by unstressable** [comment]
Looks good actually.
