### ISSUE TITLE
Crash with upcoming dev

### ISSUE THREAD

**Issue by MichaelDvP** [tp1de/ioBroker.ems-esp#84]
Nicht wirklich dringend, aber proddy hat in seinem neuen PR die Leerzeichen aus system info entfernt und das führt zu einem Crash: `TypeError: Cannot read properties of null (reading 'val') at ems_read (/opt/iobroker/node_modules/iobroker.ems-esp/lib/ems.js:294:78)`
Man kann über Umbenennungen geteilter Meinung sein, es darf auch durchaus zu Funktionseinschränkungen kommen, aber ein Crash sollte abgefangen werden. Beim ems-wert wird ja abgefangen, aber der adapter-wert wird ja nicht angelegt, bzw. nun als `esp.System.version`

**Comment by tp1de** [comment]
Danke für den Hinweis. Ich schaue nachher mal. Geänderte Namen führen aber dazu, dass im Normalfall die alten nicht gelöscht werden. Es sei den der Parameter zum Löschen ist ausgewählt.  Dann werden alle Objekte ohne Datenbankfortschreibung gelöscht und neu angelegt. Vielleicht sollte ich den Parameter standardmäßig setzen ....

**Comment by proddy** [comment]
I did remove the spaces from the JSON System Info, for example, "Network Info" to "Network," as I eventually wanted all JSON to be formatted according to the standard ISO conventions, which are either camel-case ("networkInfo") or snake-case ("network-info") and remove spaces. This makes it easier to call via HTTP without having to escape the quotes or use %20 in the URL. The KM200 follows this style too (@tp1de see your post https://github.com/emsesp/EMS-ESP32/issues/30). So "System Info" should also change at some point to either `systemInfo` or just `system`.  If it's a problem for ioBroker-ems I can easily roll back the change and then open a new issue/PR that changes everything in one go, and everywhere in EMS-ESP.

See these references:

https://restfulapi.net/valid-json-key-names/
https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Key_Names_in_JSON_Maps#Key_Names_in_JSON_Maps

**Comment by tp1de** [comment]
@proddy I understand your reasons. I just ask myself how to scope with changes in entity names in general, since old objects are not deleted automatically. Same for mqtt (HA) where  the old states became inactive. 

In general I would recommend to reduce changes in names and structure to an absolute minimum.

Is there any build for your changes which I can download for tests?

**Comment by proddy** [comment]
[EMS-ESP-3_7_0-dev_25-ESP32_16M.zip](https://github.com/user-attachments/files/16179596/EMS-ESP-3_7_0-dev_25-ESP32_16M.zip)

**Comment by tp1de** [comment]
@proddy thanks. But the JSON changes are not complete. Isn't it?

[json.txt](https://github.com/user-attachments/files/16179851/json.txt)

**Comment by proddy** [comment]
No, haven't touched that yet. I was scared. Shall I propose I new naming convention?

**Comment by tp1de** [comment]
The ioBroker adapter logic depends basically on reading 2 ems-esp entities:

(1) firmware version  old: System Info.version / new: System.version
(2) bus Id: Settings.ems bus id  - unchanged until now

(1) the firmware version is read on every polling cycle and when  a changed version is seen an instance restart is initiated
(2) the bus id is used to send raw telegrams to read ems+ / ems2.0  holidayModes and switchTimes if available

Within ha the spaces are replaced by "_" , but within ha the bus id is not seen. 
I would highly appreciate to have it available. 

My recommendation: Keep the names for mqtt (ha) and api (ioBroker) the same and only change them once.

Within ioBroker any name  with "spaces", "_", "-" or camel-case does not matter. Entities (objects) can be created any way.
I just need to adjust the code for (1) and (2) to read old and new name to keep functions alive.

While using underscores "_" for api names, there will be no need to change mqtt names .... maybe just adding the bus_id to mqtt.  Since camel-case is not used for the other entities, I think it does not make sense.

**Comment by MichaelDvP** [comment]
> Is there any build for your changes which I can download?

The PRs in dev branch have a github build in the source of PR, Here: https://github.com/proddy/EMS-ESP32/releases
But remember: these changes are in a flow until the PR is merged. Downloading and testing is just a snapshot and there could be change a few minutes later.

**Comment by proddy** [comment]
> Within ha the spaces are replaced by "_" , but within ha the bus id is not seen.

why do we need to show the BUS ID in Home Assistant? No settings are exposed to HA. You can manually create an HA sensor using the API to fetch the bus_id if needed.

**Comment by tp1de** [comment]
> why do we need to show the BUS ID in Home Assistant? No settings are exposed to HA. You can manually create an HA sensor using the API to fetch the bus_id if needed.

@proddy technically you are right. Using api I can read bus id or firmware version within HA.  Just that the names depends on the firmware version. I just thought that it makes sense to both available within the esp device in HA.

**Comment by proddy** [comment]
> > why do we need to show the BUS ID in Home Assistant? No settings are exposed to HA. You can manually create an HA sensor using the API to fetch the bus_id if needed.
> 
> @proddy technically you are right. Using api I can read bus id or firmware version within HA. Just that the names depends on the firmware version. I just thought that it makes sense to both available within the esp device in HA.

I think the way you did this now with the try/catch block is a good way to check between version formats.

```
try {busid_d = (await adapter.getStateAsync("esp.Settings.ems bus id")).val;} catch(e) {}
try {busid_d = (await adapter.getStateAsync("esp.Settings.ems_bus_id")).val;} catch(e) {}
try {busid_d = (await adapter.getStateAsync("esp.Settings.emsBusId")).val;} catch(e) {}
```

I don't see a reason to add settings (like bus ID) to HA as I don't see a use case or how it would be used.

**Comment by tp1de** [comment]
> I don't see a reason to add settings (like bus ID) to HA as I don't see a use case or how it would be used

I implemented in ioBroker and in HA an additional function to send raw telegrams to discover switchTimes and holidayModes within ems-esp (EMS+ and EMS 2.0).  I decode the received data the same way as km200 gateway does. This is fully implemented within the ioBroker adapter. The states are writable. ioBroker uses API.

Within HA I am still trying to find the right entity-types. Anyhow this function needs the bus-id. Since HA interface is based on MQTT it would be fine to avoid additional API requests and stay within MQTT.  
Whenever it works stable it might be of interest for other users as well.

Additionally I believe that firmware version is good to have in HA as well to be able to signal version changes within HA.

**Comment by proddy** [comment]
okay, i see. I'll add both version and bus_id as HA sensors. The firmware version is in HA's MQTT Device Registry but it's not easy to read. Adding a sensor will be easier.

![image](https://github.com/user-attachments/assets/d3904a8d-2387-4d7f-b49d-67bee5380dad)

If you're reading values from the EMS we can add back the `read` function which handled the control codes (using bus_id, ems 1.0 vs 2.0). There was a reason we removed this but I can't remember anymore.

**Comment by MichaelDvP** [comment]
> There was a reason we removed this but I can't remember anymore.

We never had one, we discussed if we add it. But a read command need dest, telegram-type, offset, length, the raw send command is just the src byte longer (at this time we count every flash/ram byte for the 4M esp). The old send command sets always the ems_bus_id as source, we later changed the bus to allow any source. We can modify system/send to set the ems_bus_id when SRC is zero, giving a bit flexibility without knowing the id. Or add read/write commands.

**Comment by proddy** [comment]
ah yes, very true. I'll just add busID to the info MQTT topic, and then add them as topics to HA. I think that's the easiest.

**Comment by tp1de** [comment]
Within api bus id is decimal. For telegram, I need to transform to hex.

**Comment by tp1de** [comment]
Today I send a read request, then I need to wait  approx 300 msec for reading response.

**Comment by proddy** [comment]
Another idea is making the busid configurable in your brokerio. As 99.99% it's going to be 11 for most users.

**Comment by tp1de** [comment]
> Another idea is making the busid configurable in your brokerio. As 99.99% it's going to be 11 for most users.

The ioBroker adapter is reading anyhow from /system/info ... I started with fixed 11 and when I tested with a second gateway I was wondering why it was not working.

In HA I use node-red and the node-red mqtt nodes. In the moment with fixed bus id 11. But it is still in early test phase. I coud use a yaml file for parameters as used within HA in general. But I like to avoid any additional complexity. Since response telegram length is 82 bytes, ems-esp custom entities do not work. (and userns need to know the respective telegram types).

It is not important for me, I just thought that it makes sense to have the data available.

I am trying to link the switchTimes data to a corresponding scheduler card and integration. This is a bit tricky.
Much easy is to change the hc or dwh to manual and set the values by HA scheduler from HACS.
But I will continue testing.

**Comment by proddy** [comment]
That would be a great addition if you can get HA to work with switchTimes. I looked into https://github.com/nielsfaber/scheduler-card and https://github.com/nielsfaber/scheduler-component and something like the picture below is really cool.

![image](https://github.com/user-attachments/assets/6b2d8608-e24a-47c8-ae9b-44fd1079546b)

**Comment by proddy** [comment]
think this can be closed now?
